#!/bin/bash

# sources: 
# https://www.digitalocean.com/community/tutorials/execute-command-shell-script
# https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script

npx ts-node src/fleet.ts $@
